added prakharcode
OpenAstronomy/Universe_OA pull request #13
Opened 2018-04-30 09:02 UTC by prakharcode

2018-05-05 18:02 UTC, dpshelio requested changes
If you think you won't use it for other stuff then it's ok

2018-05-05 18:02 UTC, dpshelio commented on gsoc.yml
> +    rss_feed: "https://prakharcode.github.io/feed.xml"
@prakharcode would it be possible to get the feed only for the GSoC tag? You may want to write about other stuff in your blog.

2018-05-05 19:41 UTC, prakharcode commented
@dpshelio changed the field to specific gsoc tag.
thanks to @oxinabox 's code for tag-specific feed generation.

2018-05-06 01:30 UTC, oxinabox commented
I stole the idea from someone else in turn :-)

2018-05-06 19:21 UTC, dpshelio approved these changes

2018-05-06 19:21 UTC, dpshelio commented on gsoc.yml
> +    rss_feed: "https://prakharcode.github.io/gsoc_feed.xml"
Thanks!

2018-05-06 19:22 UTC, merged