Add the RSS feed link
OpenAstronomy/Universe_OA pull request #66
Opened 2022-06-26 12:28 UTC by arunavabasu-03

### Done #61 

- [ ] RSS feed link added by [@arunavabasu-03](https://github.com/arunavabasu-03)

2022-06-26 12:45 UTC, dpshelio requested changes

2022-06-26 12:45 UTC, dpshelio commented on gsoc.yml
> +    rss_feed: "https://gsoc.arunavabasu.com/"
We need the link to the rss feed.

2022-06-28 14:06 UTC, arunavabasucom commented
@dpshelio @bsipocz Done 😀 .

2022-06-28 14:41 UTC, bsipocz approved these changes

2022-06-28 14:41 UTC, merged

2022-06-28 14:41 UTC, bsipocz commented
thanks!